### ISSUE TITLE
Question: C-x k or q shortcuts

### ISSUE THREAD

**Issue by stefanhusmann** [parkouss/webmacs#30]
The shortcuts only work if the buffer was called from another buffer using C-x f or so. They do not work for buffers opend externally, e.g. by a "browse-url" call from emacs or clickin on an url in a mail.
Or is this another command?

**Comment by stefanhusmann** [comment]
I start webmacs from my .xinitrc with a default page opening. If I do a "C-x f" and type another orl, webmacs opend that one as expected, and with "q" or "C-x k" I can close the buffer, falling back to the page first started. 

But "q" or "C-x k" cannot close the initial window.

Similar: If I get a mail with an URL in it, I can click on it and it opens in a new webmacs instance. This instance cannot be closed with "q" or "C-x k". 

Or I use stumpwm and its prefix key (Super-A in my case) together with "!" This gives be a prompt in which I can start things. If I start webmacs, the window cannot opens, but again cannot be closed. 

emacs browse-url feature wors, but was only meant as an example. It seems tha any "first instance" of webmacs cannot be closed without using xkill.

**Comment by parkouss** [comment]
Oh, I think I get it then - this is a "feature", as you can't kill the last buffer using q or c-x k else it would kill the browser (you can still use C-x C-c). I guess we can set a variable to be able to customize this behavior. Is it what's happenning?

As for what you describe, this sounds like a bug: webmacs should not open a new instance each time you call it - but I just fixed an error that leaked the socket file, and maybe you still have a webmacs.ipc file in /tmp because of that bug? (please remove it by hand if so). Anyway this is something else, if there is something wrong or a new behavior desired for that, we can discuss it in another issue.

**Comment by stefanhusmann** [comment]
C-x C-c like in emacs - I should have tried that! Sorry for the stupid question.
